---

- name: join vm as worker to k3s
  hosts: workers
  become: yes
  vars_files:
    - secrets.yaml
  tasks:
    - name: install k3s agent and join cluster
      shell: |
       curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.34.5+k3s1 K3S_URL=https://192.168.1.171:6443 K3S_TOKEN={{join_token}} sh -
      args:
        creates: /etc/systemd/system/k3s-agent.service
